name: CI

on:
  push:
    branches:
      - current

  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version: [28.2, snapshot]

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Checkout Faff Theme
        uses: actions/checkout@v3

      - name: Run tests
        run: make test
